### ISSUE TITLE
What data is placed in VALHALLA_DOCKER_DATAPATH

### ISSUE THREAD

**Issue by sindile** [valhalla/docker#31]
From the documentation there is reference to a data path 
VALHALLA_DOCKER_DATAPATH=/some/path/to/data docker-compose -f docker-compose-{ppa|source}.yml up

What is not clear to me is whether:
1. I put .pbf file
or
2. I put tiles. If it is tiles how do I generate them.

**Comment by kevinkreiser** [comment]
It is the latter. You generate them with the `valhalla_build_tiles` program which is also available inside the container. You can use `docker run` to build the tiles from inside the container and then start the service in the container afterwards.

**Comment by sindile** [comment]
Thank you.
