### ISSUE TITLE
Segmentation fault (core dumped) while valhalla_build_tiles

### ISSUE THREAD

**Issue by benpetsch** [valhalla/docker#32]
I'm trying to youse valhalla docker as a self hosted isochrone service.

Preparing the tiles fails. Because:

Running the command `valhalla_build_tiles` from inside the docker results in `Segmentation fault (core dumped)`.

-----
Steps to reproduce:

1. clone this repo
2. mkdir data & download greece-latest.osm.pbf (only 156mb)
`mkdir data && cd data && wget http://download.geofabrik.de/europe/greece-latest.osm.pbf`
3. Bringing up the container with via docker-compose:
`VALHALLA_DOCKER_DATAPATH=/my/custom/path/to/data docker-compose -f docker-compose-ppa.yml up`
3. enter the docker:
`docker exec -it valhalla_valhalla_1 /bin/bash`
4. generate tiles from osm.pbf
`valhalla_build_tiles -c conf/valhalla.json data/valhalla/greece-latest.osm.pbf`
=> Error
`Segmentation fault (core dumped)`

Am I missing something?

**Comment by kevinkreiser** [comment]
I think there was a bug in the version of the container That is up there now. Can you docker build from source and see if it still happens? We can update the dockerhub container as well. I'll let you know when we do

**Comment by benpetsch** [comment]
Thanks for the fast answer.

1.
Building this repo from source 
`docker build -t valhalla -f Dockerfile-source .`
results in:
`No package 'liblz4' found
[...]
The command '/bin/sh -c /scripts/install_from_source.sh' returned a non-zero code: 1`

2.
Same steps like my first post, but `docker-compose-source.yml` results as well in `Segmentation fault (core dumped)`

-----
The docker-compose-source/ppa.yml uses the image `1.1.20` is there any other working last version I could use?

**Comment by kevinkreiser** [comment]
The from source script was out of date so I updated it a second ago. Can you give it a try again?

**Comment by benpetsch** [comment]
Unfortunately this does not resolve the issue.
Results in same error while building from source via:
`docker build -f Dockerfile-source --tag valhalla .`

**Comment by kevinkreiser** [comment]
turned out to be a bit more complicated. anyway i just tested with `./build.sh source 2.4.7` and it worked!

**Comment by benpetsch** [comment]
works like a charm. Thanks for the support.
