### ISSUE TITLE
naive question - where can I get / how I provide data for Valhalla?

### ISSUE THREAD

**Issue by Casyfill** [valhalla/docker#36]
sample extracts [here](https://mapzen.com/blog/a-routing-engine-of-ones-own/) seems to be gone...

**Comment by dnesbitt61** [comment]
The Valhalla readme has some instructions: https://github.com/valhalla/valhalla under the Running section.  It recommends trying Geofabrik to get a country or state/province extract:

wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf

**Comment by drewda** [comment]
@Casyfill FYI, another option for downloading pre-built Valhalla tiles is https://www.interline.io/valhalla/tilepacks/ (Note that this is a paid service, for developers and companies that need to run their own global Valhalla deployments.)
