### ISSUE TITLE
valhalla/docker:latest not found

### ISSUE THREAD

**Issue by Andygol** [valhalla/docker#37]
Running `docker pull valhalla/docker` causes this message

> Using default tag: latest
> Error response from daemon: manifest for valhalla/docker:latest not found

Could you update configuration for pulling Valhalla from hub.docker.com?

**Comment by gknisely** [comment]
Can you try now?  I would use source tag as ppa is a little behind.

**Comment by Andygol** [comment]
@gknisely 
I've just tried again to run
>docker pull valhalla/docker

and nothing changed. I got the same error message 😞

**Comment by Andygol** [comment]
Here is a description of similar issue in docker docs
https://success.docker.com/article/manifest-not-found-for-dtr-image-tag

Maybe it helps

**Comment by gknisely** [comment]
try this for now.  docker pull valhalla/docker:source-1.4.6

**Comment by Andygol** [comment]
> docker pull valhalla/docker:source-1.4.6

👆It is working. But here we need to explicitly specify the current version (source-1.4.6).

What about universal solution for pulling latest image by default?

**Comment by Andygol** [comment]
@gknisely 
Could you **tag** `valhalla/docker:source-1.4.6` as `latest`
```
docker tag 834a779ade36 valhalla/docker:latest
docker push valhalla/docker:latest
```
where `834a779ade36` is a local id of `valhalla/docker:source-1.4.6`

**Comment by gknisely** [comment]
building now

**Comment by Andygol** [comment]
@gknisely 
🙇 Thank you, for now 
```
docker pull valhalla/docker
```
works as expected.


```
andygol$ docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
valhalla/docker     latest              4bb4c09f619c        10 minutes ago      2.02GB
ubuntu              16.04               c9d990395902        7 days ago          113MB
```

It is good to close this issue.

**Comment by gknisely** [comment]
you're welcome @Andygol
