### ISSUE TITLE
Running The Docker Image

### ISSUE THREAD

**Issue by mem48** [valhalla/docker#38]
I'm having trouble getting started I can pull the docker image

`docker run -it valhalla/docker:latest`

And the I get

```
2018-05-11 12:42:46,296 CRIT Supervisor running as root (no user in config file)
2018/05/11 12:42:47.348240 [WARN] Tile extract could not be loaded
2018/05/11 12:42:47.355694 [WARN] Tile extract could not be loaded
2018/05/11 12:42:47.361239 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
```

I'm on Windows 10, how do i provide the data and what do I expect to happen?

I.e. can you point me to some documentation?

**Comment by gknisely** [comment]
@mem48  You need to generate the tiles with the valhalla_build_tiles program.  It is also available inside the container.  You use docker run to build the tiles from inside the container and then start the service in the container afterwards.  This [getting started guide ](https://github.com/valhalla/valhalla/blob/master/docs/mjolnir/getting_started_guide.md) should help you out.   Only difference is that you are using docker.
