### ISSUE TITLE
Publish Meili as an image

### ISSUE THREAD

**Issue by chrisfosterelli** [valhalla/docker#4]
This was first raised in https://github.com/valhalla/docker/issues/3, related to https://github.com/valhalla/meili/issues/43.

Because building the Meili image manually takes quite a while and requires a fair amount of RAM, it could save lots of people a bunch of time by publishing it on Docker Hub. @kevinkreiser mentioned it may be easier to publish it as a separate image, rather than merged into the current image.

**Comment by ptpt** [comment]
Checkout the latest meili Dockerfile @chrisfosterelli. Now it installs meili via apt-get instead of pull the source and compile from scratch. It should take much less time than it was before.

It is just a workaround. We should still wait for an official docker image on Docker Hub.

**Comment by chrisfosterelli** [comment]
@ptpt Thanks! That is much faster and helps a lot in the meantime.

**Comment by ptpt** [comment]
@chrisfosterelli we can use this repo as a temporary solution, before the official docker hub gets ready.
```
docker pull ptpt/meili
```

**Comment by chrisfosterelli** [comment]
Since Meili is integrated into the main Valhalla repository now (which is published as a docker image on docker hub), can this be closed?
